name: CI/CD Pipeline

on:
  push:
    branches:
      - main # Trigger on push to main branch
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Python
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      # Install dependencies
      - name: Install dependencies
        run: |
          pip install --upgrade pip  # Ensure pip is upgraded
          pip install -r requirements.txt
          pip install pytest  # Ensure pytest is installed

      # Verify pytest installation
      - name: Verify pytest installation
        run: |
          pip show pytest  # Check if pytest is installed
          which pytest     # Check pytest path

      # List project files for debugging
      - name: List project files
        run: ls -R # List all files and folders recursively

      # Run tests
      - name: Run tests
        run: |
          pytest test_app.py  # Run tests from test_app.py

      # Build Docker image
      - name: Build Docker image
        run: docker build -t sayanghorai321/ml-flask-app:latest .

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Push Docker image to Docker Hub
      - name: Push Docker image
        run: docker push sayanghorai321/ml-flask-app:latest
